### ISSUE TITLE
Fatal Issue: Cannot redeclare ctype_digit()

### ISSUE THREAD

**Issue by issmirnov** [splitbrain/dokuwiki-template-twigstarter#1]
Hello,

There is a fatal bug in this template:

```
2020/02/05 10:12:16 [error] 339#339: *47 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare ctype_digit() 

(previously declared in /app/dokuwiki/inc/compatibility.php:31) in 
/config/dokuwiki/lib/tpl/dokuwind/vendor/symfony/polyfill-ctype/bootstrap.php
 on line 18" while reading response header from upstream, client: 172.18.0.1, server: _, 

request: "GET /doku.php?id=start&do=admin&page=config HTTP/1.1", 
upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8080", 
referrer: "http://localhost:8080/doku.php?id=start&do=admin&page=config"
```

Steps to reproduce:

1. Clean install Dokuwiki
2. Open Extension manager and install the twigstarter template
3. Switch to the template in config settings

Analysis:

It seems that the [compatibility.php](https://github.com/splitbrain/dokuwiki/blob/cbaf278c50e5baf946b3bd606c369735fe0953be/inc/compatibility.php#L23) logic is getting loaded first, and then when the vendor/symphony/polyfill code runs there's an issue with the `ctype_digit` function already being declared. I don't know enough about PHP load order or what `symphony` is for to provide useful debugging here.

**Comment by splitbrain** [comment]
what php version are you using?

**Comment by issmirnov** [comment]
PHP7 from [this docker base](https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/Dockerfile#L16) in [this image](https://github.com/linuxserver/docker-dokuwiki/blob/master/Dockerfile#L24)

**Comment by splitbrain** [comment]
`ctype_digit` should exist natively in PHP7 so neither compatibility layer should be loaded at all.

I notice that your error message is referring to a `lib/tpl/dokuwind/` directory not `lib/tpl/twigstarter`.

**Comment by issmirnov** [comment]
I cloned twigstarter and renamed it to dokuwind for a WIP project. I checked in the same environment, and installing the twigstarter template through the extension UI seems to have the same issue.

**Comment by issmirnov** [comment]
I'm using the following docker config:

```
---
version: "2"
services:
  dokuwiki:
    image: linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    ports:
      - 80:80
    restart: unless-stopped
```

If this looks like a PHP issue, I can open an issue upstream on https://github.com/linuxserver/docker-dokuwiki
